# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class COM(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(250, 348)
        Widget.setMinimumSize(QtCore.QSize(250, 0))
        Widget.setMaximumSize(QtCore.QSize(250, 348))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GURIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Widget.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbConnection = QtWidgets.QGroupBox(Widget)
        self.gbConnection.setObjectName("gbConnection")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gbConnection)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leIP = QtWidgets.QLineEdit(self.gbConnection)
        self.leIP.setObjectName("leIP")
        self.horizontalLayout_2.addWidget(self.leIP)
        self.bConnect = QtWidgets.QPushButton(self.gbConnection)
        self.bConnect.setCheckable(True)
        self.bConnect.setObjectName("bConnect")
        self.horizontalLayout_2.addWidget(self.bConnect)
        self.verticalLayout.addWidget(self.gbConnection)
        self.gbControls = QtWidgets.QGroupBox(Widget)
        self.gbControls.setObjectName("gbControls")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbControls)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lM = QtWidgets.QLabel(self.gbControls)
        self.lM.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lM.setObjectName("lM")
        self.gridLayout_3.addWidget(self.lM, 0, 0, 1, 1)
        self.lK2 = QtWidgets.QLabel(self.gbControls)
        self.lK2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lK2.setObjectName("lK2")
        self.gridLayout_3.addWidget(self.lK2, 0, 1, 1, 1)
        self.lK1 = QtWidgets.QLabel(self.gbControls)
        self.lK1.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lK1.setObjectName("lK1")
        self.gridLayout_3.addWidget(self.lK1, 0, 2, 1, 1)
        self.lR5 = QtWidgets.QLabel(self.gbControls)
        self.lR5.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lR5.setObjectName("lR5")
        self.gridLayout_3.addWidget(self.lR5, 0, 3, 1, 1)
        self.lR4 = QtWidgets.QLabel(self.gbControls)
        self.lR4.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lR4.setObjectName("lR4")
        self.gridLayout_3.addWidget(self.lR4, 0, 4, 1, 1)
        self.lR3 = QtWidgets.QLabel(self.gbControls)
        self.lR3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lR3.setObjectName("lR3")
        self.gridLayout_3.addWidget(self.lR3, 0, 5, 1, 1)
        self.lR2 = QtWidgets.QLabel(self.gbControls)
        self.lR2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lR2.setObjectName("lR2")
        self.gridLayout_3.addWidget(self.lR2, 0, 6, 1, 1)
        self.lR1 = QtWidgets.QLabel(self.gbControls)
        self.lR1.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lR1.setObjectName("lR1")
        self.gridLayout_3.addWidget(self.lR1, 0, 7, 1, 1)
        self.chbM = QtWidgets.QCheckBox(self.gbControls)
        self.chbM.setText("")
        self.chbM.setObjectName("chbM")
        self.gridLayout_3.addWidget(self.chbM, 1, 0, 1, 1)
        self.chbK2 = QtWidgets.QCheckBox(self.gbControls)
        self.chbK2.setText("")
        self.chbK2.setObjectName("chbK2")
        self.gridLayout_3.addWidget(self.chbK2, 1, 1, 1, 1)
        self.chbK1 = QtWidgets.QCheckBox(self.gbControls)
        self.chbK1.setText("")
        self.chbK1.setObjectName("chbK1")
        self.gridLayout_3.addWidget(self.chbK1, 1, 2, 1, 1)
        self.chbR5 = QtWidgets.QCheckBox(self.gbControls)
        self.chbR5.setText("")
        self.chbR5.setObjectName("chbR5")
        self.gridLayout_3.addWidget(self.chbR5, 1, 3, 1, 1)
        self.chbR4 = QtWidgets.QCheckBox(self.gbControls)
        self.chbR4.setText("")
        self.chbR4.setObjectName("chbR4")
        self.gridLayout_3.addWidget(self.chbR4, 1, 4, 1, 1)
        self.chbR3 = QtWidgets.QCheckBox(self.gbControls)
        self.chbR3.setText("")
        self.chbR3.setObjectName("chbR3")
        self.gridLayout_3.addWidget(self.chbR3, 1, 5, 1, 1)
        self.chbR2 = QtWidgets.QCheckBox(self.gbControls)
        self.chbR2.setText("")
        self.chbR2.setObjectName("chbR2")
        self.gridLayout_3.addWidget(self.chbR2, 1, 6, 1, 1)
        self.chbR1 = QtWidgets.QCheckBox(self.gbControls)
        self.chbR1.setText("")
        self.chbR1.setObjectName("chbR1")
        self.gridLayout_3.addWidget(self.chbR1, 1, 7, 1, 1)
        self.verticalLayout.addWidget(self.gbControls)
        self.gbStates = QtWidgets.QGroupBox(Widget)
        self.gbStates.setObjectName("gbStates")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbStates)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lMx = QtWidgets.QLabel(self.gbStates)
        self.lMx.setMinimumSize(QtCore.QSize(20, 20))
        self.lMx.setMaximumSize(QtCore.QSize(40, 40))
        self.lMx.setAlignment(QtCore.Qt.AlignCenter)
        self.lMx.setObjectName("lMx")
        self.horizontalLayout.addWidget(self.lMx)
        self.lKx2 = QtWidgets.QLabel(self.gbStates)
        self.lKx2.setMinimumSize(QtCore.QSize(20, 20))
        self.lKx2.setMaximumSize(QtCore.QSize(40, 40))
        self.lKx2.setAlignment(QtCore.Qt.AlignCenter)
        self.lKx2.setObjectName("lKx2")
        self.horizontalLayout.addWidget(self.lKx2)
        self.lKx1 = QtWidgets.QLabel(self.gbStates)
        self.lKx1.setMinimumSize(QtCore.QSize(20, 20))
        self.lKx1.setMaximumSize(QtCore.QSize(40, 40))
        self.lKx1.setAlignment(QtCore.Qt.AlignCenter)
        self.lKx1.setObjectName("lKx1")
        self.horizontalLayout.addWidget(self.lKx1)
        self.lRx5 = QtWidgets.QLabel(self.gbStates)
        self.lRx5.setMinimumSize(QtCore.QSize(20, 20))
        self.lRx5.setMaximumSize(QtCore.QSize(40, 40))
        self.lRx5.setAlignment(QtCore.Qt.AlignCenter)
        self.lRx5.setObjectName("lRx5")
        self.horizontalLayout.addWidget(self.lRx5)
        self.lRx4 = QtWidgets.QLabel(self.gbStates)
        self.lRx4.setMinimumSize(QtCore.QSize(20, 20))
        self.lRx4.setMaximumSize(QtCore.QSize(40, 40))
        self.lRx4.setAlignment(QtCore.Qt.AlignCenter)
        self.lRx4.setObjectName("lRx4")
        self.horizontalLayout.addWidget(self.lRx4)
        self.lRx3 = QtWidgets.QLabel(self.gbStates)
        self.lRx3.setMinimumSize(QtCore.QSize(20, 20))
        self.lRx3.setMaximumSize(QtCore.QSize(40, 40))
        self.lRx3.setAlignment(QtCore.Qt.AlignCenter)
        self.lRx3.setObjectName("lRx3")
        self.horizontalLayout.addWidget(self.lRx3)
        self.lRx2 = QtWidgets.QLabel(self.gbStates)
        self.lRx2.setMinimumSize(QtCore.QSize(20, 20))
        self.lRx2.setMaximumSize(QtCore.QSize(40, 40))
        self.lRx2.setAlignment(QtCore.Qt.AlignCenter)
        self.lRx2.setObjectName("lRx2")
        self.horizontalLayout.addWidget(self.lRx2)
        self.lRx1 = QtWidgets.QLabel(self.gbStates)
        self.lRx1.setMinimumSize(QtCore.QSize(20, 20))
        self.lRx1.setMaximumSize(QtCore.QSize(40, 40))
        self.lRx1.setAlignment(QtCore.Qt.AlignCenter)
        self.lRx1.setObjectName("lRx1")
        self.horizontalLayout.addWidget(self.lRx1)
        self.verticalLayout.addWidget(self.gbStates)
        self.gbCurrents = QtWidgets.QGroupBox(Widget)
        self.gbCurrents.setObjectName("gbCurrents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbCurrents)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lCurrent1Name = QtWidgets.QLabel(self.gbCurrents)
        self.lCurrent1Name.setObjectName("lCurrent1Name")
        self.gridLayout_2.addWidget(self.lCurrent1Name, 0, 0, 1, 1)
        self.lCurrent1Value = QtWidgets.QLabel(self.gbCurrents)
        self.lCurrent1Value.setObjectName("lCurrent1Value")
        self.gridLayout_2.addWidget(self.lCurrent1Value, 0, 1, 1, 1)
        self.lCurrent2Name = QtWidgets.QLabel(self.gbCurrents)
        self.lCurrent2Name.setObjectName("lCurrent2Name")
        self.gridLayout_2.addWidget(self.lCurrent2Name, 1, 0, 1, 1)
        self.lCurrent2Value = QtWidgets.QLabel(self.gbCurrents)
        self.lCurrent2Value.setObjectName("lCurrent2Value")
        self.gridLayout_2.addWidget(self.lCurrent2Value, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbCurrents)
        self.gbAlarms = QtWidgets.QGroupBox(Widget)
        self.gbAlarms.setObjectName("gbAlarms")
        self.gridLayout = QtWidgets.QGridLayout(self.gbAlarms)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lAlarmM = QtWidgets.QLabel(self.gbAlarms)
        self.lAlarmM.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lAlarmM.setObjectName("lAlarmM")
        self.gridLayout.addWidget(self.lAlarmM, 0, 0, 1, 1)
        self.lAlarmK2 = QtWidgets.QLabel(self.gbAlarms)
        self.lAlarmK2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lAlarmK2.setObjectName("lAlarmK2")
        self.gridLayout.addWidget(self.lAlarmK2, 0, 1, 1, 1)
        self.lAlarmK1 = QtWidgets.QLabel(self.gbAlarms)
        self.lAlarmK1.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lAlarmK1.setObjectName("lAlarmK1")
        self.gridLayout.addWidget(self.lAlarmK1, 0, 2, 1, 1)
        self.lAlarmR5 = QtWidgets.QLabel(self.gbAlarms)
        self.lAlarmR5.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lAlarmR5.setObjectName("lAlarmR5")
        self.gridLayout.addWidget(self.lAlarmR5, 0, 3, 1, 1)
        self.lAlarmR4 = QtWidgets.QLabel(self.gbAlarms)
        self.lAlarmR4.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lAlarmR4.setObjectName("lAlarmR4")
        self.gridLayout.addWidget(self.lAlarmR4, 0, 4, 1, 1)
        self.lAlarmR3 = QtWidgets.QLabel(self.gbAlarms)
        self.lAlarmR3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lAlarmR3.setObjectName("lAlarmR3")
        self.gridLayout.addWidget(self.lAlarmR3, 0, 5, 1, 1)
        self.lAlarmR2 = QtWidgets.QLabel(self.gbAlarms)
        self.lAlarmR2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lAlarmR2.setObjectName("lAlarmR2")
        self.gridLayout.addWidget(self.lAlarmR2, 0, 6, 1, 1)
        self.lAlarmR1 = QtWidgets.QLabel(self.gbAlarms)
        self.lAlarmR1.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lAlarmR1.setObjectName("lAlarmR1")
        self.gridLayout.addWidget(self.lAlarmR1, 0, 7, 1, 1)
        self.lAlarmEcho = QtWidgets.QLabel(self.gbAlarms)
        self.lAlarmEcho.setFrameShape(QtWidgets.QFrame.Panel)
        self.lAlarmEcho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lAlarmEcho.setAlignment(QtCore.Qt.AlignCenter)
        self.lAlarmEcho.setObjectName("lAlarmEcho")
        self.gridLayout.addWidget(self.lAlarmEcho, 1, 0, 1, 8)
        self.verticalLayout.addWidget(self.gbAlarms)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Керування РКП"))
        Widget.setToolTip(_translate("Widget", "Керування розгалуджувально-комутаційним пристроєм"))
        self.gbConnection.setTitle(_translate("Widget", "Параметри з\'єднання"))
        self.leIP.setInputMask(_translate("Widget", "000.000.000.000:0000;_"))
        self.bConnect.setText(_translate("Widget", "З\'єднати"))
        self.gbControls.setTitle(_translate("Widget", "Управління"))
        self.lM.setText(_translate("Widget", " M"))
        self.lK2.setText(_translate("Widget", "K2"))
        self.lK1.setText(_translate("Widget", "K1"))
        self.lR5.setText(_translate("Widget", "R5"))
        self.lR4.setText(_translate("Widget", "R4"))
        self.lR3.setText(_translate("Widget", "R3"))
        self.lR2.setText(_translate("Widget", "R2"))
        self.lR1.setText(_translate("Widget", "R1"))
        self.chbM.setToolTip(_translate("Widget", "Переключення каналів конвертора"))
        self.chbK2.setToolTip(_translate("Widget", "Включення живлення каналу №2 конвертора"))
        self.chbK1.setToolTip(_translate("Widget", "Включення живлення каналу №1 конвертора"))
        self.chbR5.setToolTip(_translate("Widget", "Включення живлення приймача №5"))
        self.chbR4.setToolTip(_translate("Widget", "Включення живлення приймача №4"))
        self.chbR3.setToolTip(_translate("Widget", "Включення живлення приймача №3"))
        self.chbR2.setToolTip(_translate("Widget", "Включення живлення приймача №2"))
        self.chbR1.setToolTip(_translate("Widget", "Включення живлення приймача №1"))
        self.gbStates.setTitle(_translate("Widget", "Стани"))
        self.lMx.setText(_translate("Widget", " Mx"))
        self.lKx2.setText(_translate("Widget", "Kx2"))
        self.lKx1.setText(_translate("Widget", "Kx1"))
        self.lRx5.setText(_translate("Widget", "Rx5"))
        self.lRx4.setText(_translate("Widget", "Rx4"))
        self.lRx3.setText(_translate("Widget", "Rx3"))
        self.lRx2.setText(_translate("Widget", "Rx2"))
        self.lRx1.setText(_translate("Widget", "Rx1"))
        self.gbCurrents.setTitle(_translate("Widget", "Струми конвертора, мА"))
        self.lCurrent1Name.setText(_translate("Widget", "Канал 1:"))
        self.lCurrent1Value.setText(_translate("Widget", "н/д"))
        self.lCurrent2Name.setText(_translate("Widget", "Канал 2:"))
        self.lCurrent2Value.setText(_translate("Widget", "н/д"))
        self.gbAlarms.setTitle(_translate("Widget", "Аварії"))
        self.lAlarmM.setText(_translate("Widget", " M"))
        self.lAlarmK2.setText(_translate("Widget", "K2"))
        self.lAlarmK1.setText(_translate("Widget", "K1"))
        self.lAlarmR5.setText(_translate("Widget", "R5"))
        self.lAlarmR4.setText(_translate("Widget", "R4"))
        self.lAlarmR3.setText(_translate("Widget", "R3"))
        self.lAlarmR2.setText(_translate("Widget", "R2"))
        self.lAlarmR1.setText(_translate("Widget", "R1"))
        self.lAlarmEcho.setText(_translate("Widget", "Аварія луни"))

