# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_bd_r.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame
from PyQt5.QtCore import QDir
from urh.dev import config
class UI_TAB(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1369, 885)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setObjectName("pushButton1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton1)
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setObjectName("pushButton2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton2)
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setObjectName("pushButton3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton3)

        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setObjectName("pushButton4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton4)

        self.pushButton5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton5.setObjectName("pushButton5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton5)
        self.gridLayout.addLayout(self.formLayout, 0, 1, 2, 1)

        self.pushButton6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton6.setObjectName("pushButton6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton6)
        self.gridLayout.addLayout(self.formLayout, 0, 1, 2, 1)





        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setToolTip("")
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.tableWidget.setHorizontalHeaderLabels(("Назва", "Тип", "Частота", "Ширина спектру", "Тип модуляцii",
                                                    "Тривалiсть iмпульсу", "Перiод слiдування", "Коментар",
                                                    "Зображення", "Path", "pulse"))
        self.tableWidget.setMouseTracking(True)

        for column_hidden in (0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11):
            self.tableWidget.hideColumn(column_hidden)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)

        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tab.sizePolicy().hasHeightForWidth())
        self.main_tab.setSizePolicy(sizePolicy)
        self.main_tab.setMinimumSize(QtCore.QSize(200, 400))
        self.main_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_tab.setStyleSheet("")
        self.main_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.main_tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.main_tab.setMovable(False)
        self.main_tab.setObjectName("main_tab")
        self.signal_properties_tab = QtWidgets.QWidget()
        self.signal_properties_tab.setMinimumSize(QtCore.QSize(0, 0))
        self.signal_properties_tab.setBaseSize(QtCore.QSize(0, 0))
        self.signal_properties_tab.setObjectName("signal_properties_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.signal_properties_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")

        self.tableWidget_2 = QtWidgets.QTableWidget(self.signal_properties_tab)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(9)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(2048, 248))
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        # self.tableWidget_2.horizontalHeader().resizeContentsPrecision()
#---------- don't edit selected yacheyka and selected rows--------------------------
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
# ---------- size of column--------------------------
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        #---------- size of column--------------------------
        self.tableWidget_2.horizontalHeader().resizeSection(0, 180)
        self.tableWidget_2.horizontalHeader().resizeSection(1, 110)
        self.tableWidget_2.horizontalHeader().resizeSection(2, 180)
        self.tableWidget_2.horizontalHeader().resizeSection(3, 110)
        self.tableWidget_2.horizontalHeader().resizeSection(4, 185)
        self.tableWidget_2.horizontalHeader().resizeSection(5, 180)
        #self.tableWidget_2.horizontalHeader().resizeSection(6, 350)


        self.tableWidget_2.setHorizontalHeaderLabels(
            ("Дата", "Частота, МГц", "Ширина запису, МГц", "Модуляція","Тривалість імпульсу, мкс", "Період слідування, мкс",
             "Коментар", "Шлях", "id"))
        self.tableWidget_2.setMouseTracking(False)

        self.tableWidget_2.hideColumn(3)

        self.tableWidget_2.hideColumn(8)

        self.pushButton22 = QtWidgets.QPushButton()
        self.pushButton22.setObjectName("pushButton")

        # ---------------------

        # self.tableWidget_2.setSizeAdjustPolicy(
        #     QtWidgets.QAbstractScrollArea.AdjustToContents)

        self.gridLayout_3.addWidget(self.tableWidget_2, 3, 0, 1, 12)

        # self.label = QtWidgets.QLabel(self.signal_properties_tab)
        # font = QtGui.QFont()
        # font.setPointSize(24)
        # self.label.setFont(font)
        # self.label.setAlignment(QtCore.Qt.AlignCenter)
        # self.label.setObjectName("label")
        # self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_date = QtWidgets.QLineEdit(self.signal_properties_tab)
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.lineEdit_date.hide()
#-------------------
        self.lineEdit_image = QtWidgets.QLineEdit(self.signal_properties_tab)
        self.lineEdit_image.setObjectName("lineEdit_image")
        self.lineEdit_image.hide()

        self.lineEdit_img = QtWidgets.QLineEdit(self.signal_properties_tab)
        self.lineEdit_img.setObjectName("lineEdit_img")
        self.lineEdit_img.hide()

        self.lineEdit_id = QtWidgets.QLineEdit(self.signal_properties_tab)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.lineEdit_id.hide()
#-------------------



        self.lineEdit_Name = QtWidgets.QLineEdit(self.signal_properties_tab)
        self.lineEdit_Name.setObjectName("lineEdit_2")
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lineEdit_Name.setFont(font)
        self.lineEdit_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_3.addWidget(self.lineEdit_Name, 0, 0, 1, 12)

        self.groupBox = QtWidgets.QGroupBox(self.signal_properties_tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_17 = QtWidgets.QFrame(self.groupBox)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_2.addWidget(self.line_17, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_12 = QtWidgets.QFrame(self.groupBox)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_2.addWidget(self.line_12)
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_2.addWidget(self.label_30)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.line_14 = QtWidgets.QFrame(self.groupBox)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_2.addWidget(self.line_14)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_13 = QtWidgets.QFrame(self.groupBox)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_3.addWidget(self.line_13)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.line_6 = QtWidgets.QFrame(self.groupBox)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.line_7 = QtWidgets.QFrame(self.groupBox)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_3.addWidget(self.lineEdit_4)
        self.line_8 = QtWidgets.QFrame(self.groupBox)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_3.addWidget(self.line_8)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_3.addWidget(self.lineEdit_5)
        self.line_9 = QtWidgets.QFrame(self.groupBox)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_3.addWidget(self.line_9)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_3.addWidget(self.lineEdit_6)
        self.line_10 = QtWidgets.QFrame(self.groupBox)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_3.addWidget(self.line_10)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_3.addWidget(self.lineEdit_7)
        self.line_15 = QtWidgets.QFrame(self.groupBox)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_3.addWidget(self.line_15)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 3, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.groupBox)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_2.addWidget(self.line_11, 0, 2, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.groupBox)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_2.addWidget(self.line_16, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        # self.label_2.setMaximumSize(QtCore.QSize(300, 200))

        self.label_2.setFixedHeight(200)
        self.label_2.setFixedWidth(300)

        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(1)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../PycharmProjects/HUEKTOR/urh-2.7.5/src/urh/db/imageStation/test.jpg"))

        self.label_2.setFrameShape(QFrame.Panel)
        self.label_2.setFrameShadow(QFrame.Sunken)

        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.gridLayout_2.addWidget(self.label_2, 0, 5, 1, 1)

        self.label_14 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasWidthForHeight())
        self.label_14.setFrameShape(QFrame.Panel)
        self.label_14.setFrameShadow(QFrame.Sunken)

        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setFixedHeight(300)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setText("")
        self.label_14.setScaledContents(True)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 6)
#--------------------------------
        self.toolbutton = QtWidgets.QToolButton(self.signal_properties_tab)
        self.toolbutton.setObjectName("toolbutton")
        icon = QtGui.QIcon.fromTheme("insert-image")
        self.toolbutton.setIcon(icon)
        self.gridLayout_3.addWidget(self.toolbutton, 2, 0, 1, 1)

        self.toolbutton.hide()
#---------------------------------

        self.lineEdit_12 = QtWidgets.QLineEdit(self.signal_properties_tab)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_3.addWidget(self.lineEdit_12, 2, 3, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.signal_properties_tab)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_3.addWidget(self.lineEdit_10, 2, 8, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.signal_properties_tab)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_3.addWidget(self.lineEdit_14, 2, 6, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.signal_properties_tab)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_3.addWidget(self.lineEdit_13, 2, 7, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.signal_properties_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_15.setSizePolicy(sizePolicy)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_3.addWidget(self.lineEdit_15, 2, 1, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.signal_properties_tab)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 2, 9, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 12)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.signal_properties_tab)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_3.addWidget(self.lineEdit_16, 2, 5, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.signal_properties_tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton2.hide()
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 10, 1, 1)
# --------------------------------
        self.main_tab.addTab(self.signal_properties_tab, "")
        self.gridLayout.addWidget(self.main_tab, 0, 2, 2, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setToolTip("")
        self.lineEdit.setStatusTip("")
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("Назва станції")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton1.setStyleSheet("background-color: green")
        self.pushButton2.setStyleSheet("background-color: red")
        self.pushButton3.setStyleSheet("background-color: ")

        self.pushButton_2.setStyleSheet("background-color: grey")
        icon = QtGui.QIcon(QDir.currentPath()+config.MY_PATH +'/find.png')
        self.pushButton_2.setIcon(icon)
        self.pushButton.setIcon(icon)




        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", " Пошук"))
        self.pushButton1.setText(_translate("MainWindow", "Створити\nеталон"))
        self.pushButton2.setText(_translate("MainWindow", "Видалити"))
        self.pushButton3.setText(_translate("MainWindow", "Внести\nзміни до\nсеансу"))
        self.pushButton4.setText(_translate("MainWindow", "Відкрити\nфайл"))
        self.pushButton5.setText(_translate("MainWindow", "Новий\nсеанс"))
        self.pushButton6.setText(_translate("MainWindow", "Відкрити\nсесію"))
        # self.label.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "Параметри сигналу та еталонний вигляд"))
        self.label_30.setText(_translate("MainWindow", "Частота, МГц"))
        self.label_4.setText(_translate("MainWindow", "Ширина спектру, МГц"))
        self.label_5.setText(_translate("MainWindow", "Тип модуляції"))
        self.label_6.setText(_translate("MainWindow", "Тривалість імпульсу, мкс"))
        self.label_7.setText(_translate("MainWindow", "Період слудування, мкс"))
        self.label_8.setText(_translate("MainWindow", "Коментар"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.signal_properties_tab), _translate("MainWindow", "Сигнал"))
        self.pushButton22.setText(_translate("MainWindow", "Оновити"))
        self.lineEdit_15.setPlaceholderText("30-12-2020 ")
        self.lineEdit_14.setPlaceholderText("Частота, МГц")
        self.lineEdit_13.setPlaceholderText("Ширина спектру, МГц")
        self.lineEdit_10.setPlaceholderText("Модуляція")
        self.lineEdit_12.setPlaceholderText("Тривалість імпульсу, мкс")
        self.lineEdit_16.setPlaceholderText("Період слідування, мкс")
        self.lineEdit_11.setPlaceholderText("Коментар")
        self.pushButton_2.setText(_translate("MainWindow", " Пошук"))
        self.toolbutton.setText(_translate("MainWindow", "..."))
        self.lineEdit_Name.setPlaceholderText("Назва станції")

        self.toolbutton.setToolTip(_translate("MainWindow", "Відкрити зображення для збереження в базу данних"))


